### ISSUE TITLE
Tipping

### ISSUE THREAD

**Issue by AtomSea** [HugPuddle/Apertus#14]
Tipping feature.
Primary: Allow Apertus users the power to tip people for their art/writing/etc within Apertus itself.
Secondary: Give one the power over multiple wallets in one interface. 
Thirdly: PurpleMonkeyDishwasher.

**Comment by embiimob** [comment]
Tipping feature has been submitted for review.

**Comment by embiimob** [comment]
Implemented in 0.3.0 beta
