### ISSUE TITLE
GUI is gooey at times - getting to function boxes can be tricky

### ISSUE THREAD

**Issue by AtomSea** [HugPuddle/Apertus#25]
In both Win 7 & 10 on desktop computers, getting to the function boxes to check or uncheck can prove difficult, and on some occasions, impossible.
This same difficulty can manifest in a small way when trying to get to the etching portion as well, but is more manageable

**Comment by embiimob** [comment]
a graphic in message pane...would expand on some windows workstations. pushing all the control elements off the screen.     
we decided to remove the graphics for now.
